title: Measure-theoretic Treatment of Statistics
categories:
- blog
conditionals:
  allslides: no
  preamble: yes
  trig: no
  stories: no
  algebra: no
  aalgebra: no
  ranalysis: no
  meastheory: no
  topspaces: no
  absmeas: no
  measprob: yes
  cvxopt: no
  sproof: no
  ynindex: no
date: Fri Aug  1 06:00:00 PDT 2025
output_markdown: ../../../_posts/2025-08-01-PDT - measure-theoretic treatment of statistics.markdown
permalink: /math/rig/measure-theoretic-treatment-of-statistics
tags:
- math
- measure theory
- statistics
def_tex: ./markdown_defs.tex
